AWSTemplateFormatVersion: '2010-09-09'
Description: Stack conditions

Conditions:
  HasDocsBucketPipelineRole:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: DocsBucketPipelineRoleArn
          - ''
  HasPipelineExecutionRoleName:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: PipelineExecutionRoleName
          - ''
  HasLandingCloudFront:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: LandingCloudFrontDistributionArn
          - ''
  HasMobileCloudFront:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: MobileCloudFrontDistributionArn
          - ''
  HasMobileWellKnownBucketPolicy:
    'Fn::Or':
      - Condition: HasDocsBucketPipelineRole
      - Condition: HasMobileCloudFront
  HasPipelineExecutionRoleAndCloudFront:
    'Fn::And':
      - Condition: HasPipelineExecutionRoleName
      - Condition: HasLandingCloudFront
      - Condition: HasMobileCloudFront
