AWSTemplateFormatVersion: '2010-09-09'

Conditions:
  HasLandingCustomDomain:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: LandingCustomDomain
          - ''
  HasMobileCustomDomain:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: MobileCustomDomain
          - ''
  HasAcmCertificate:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: AcmCertificateArn
          - ''
  HasMobileAcmCertificate:
    'Fn::Not':
      - 'Fn::Equals':
          - Ref: MobileAcmCertificateArn
          - ''
  HasMobileViewerCertificate:
    'Fn::Or':
      - Condition: HasAcmCertificate
      - Condition: HasMobileAcmCertificate
  CreateLandingWithTls:
    'Fn::And':
      - Condition: HasLandingCustomDomain
      - Condition: HasAcmCertificate
  CreateMobileWithTls:
    'Fn::And':
      - Condition: HasMobileCustomDomain
      - Condition: HasMobileViewerCertificate
